### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by juanibiapina** [orf/git-workspace#23]
I ran `git workspace update` and got a few of those errors:

```
Git exited with code 1: Resolving deltas: 100% (454/454), done.git: 'submodule' is not a git command. See 'git --help
'.
```

Also, super awesome project! I might contribute soon, because it replaces a few scripts I already have in a much better way.

**Comment by orf** [comment]
Hey @juanibiapina! Awesome, it feels good to know someone else finds it potentially useful 😂 

Can you give me a bit more information about your environment? Are you on macOS, Windows or Linux? Can you run `git --version` for me, and could you also run `git submodule --help`?

This project very much evolved from "a few scripts I already had", so there may well be rough edges. Any contributions would be amazing.

**Comment by juanibiapina** [comment]
git version 2.24.0
OSX Mojave 10.14.6

git submodule --help opens the man page for git submodule xD

**Comment by orf** [comment]
Hmm, very weird. We don't directly invoke `git submodule` - we use `--recurse-submodules` and `--recurse-submodules=on-demand` (https://github.com/orf/git-workspace/blob/master/src/repository.rs#L143)

Do you do anything _weird_ with your shell, or have any esoteric setup in any way? Because honestly, I'm not sure how to help you. It smells like a pretty environment-specific issue of some kind - that error would imply that the following directories are not in the processes PATH (these contain `git-submodule`):

1. `/usr/local/Cellar/git/2.24.0_2/libexec/git-core/`
2. `Library/Developer/CommandLineTools/usr/libexec/git-core/`

Right now tracing errors with `git-workspace` sucks. If you get invalid data back from Github or Gitlab we panic and we don't provide much in the way of traceability as to what `git` does. If you are handy with rust and feel like digging into this, I would try adding some debug [logging here](https://github.com/orf/git-workspace/blob/master/src/repository.rs#L96), and executing the process with `GIT_TRACE=1`. If the shell is not a tty then the progress bars do not show, and you will get a lot of logs.

**Comment by juanibiapina** [comment]
I can't reproduce this again, so I'll close it.
